include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
  plugins:
    - custom_lint

linter:
  rules:
    prefer_const_constructors: true
    always_use_package_imports: true
