name: ride_booking_app
description: "Basic Ride Booking App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  async: ^2.12.0
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  google_maps_flutter: ^2.11.0
  intl: any
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  retry: ^3.1.2
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
